apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: {{ include "k0smotroncontrolplane.name" . }}
spec:
  replicas: {{ .Values.controlPlaneNumber }}
  version: {{ .Values.k0s.version | replace "+" "-" }}
  {{- with .Values.k0smotron.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  controllerPlaneFlags:
  - "--enable-cloud-provider=true"
  - "--debug=true"
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: k0s
    spec:
      network:
        provider: calico
        calico:
          mode: vxlan
      extensions:
        helm:
          repositories:
            - name: openstack
              url: https://github.com/kubernetes/cloud-provider-openstack
          charts:
            - name: openstack-ccm
              chartname: openstack/openstack-cloud-controller-manager
              version: 2.31.1
              order: 1
              namespace: kube-system
              values: |
                cloudConfig:
                  global:
                    auth-url: {{ .Values.openstack.authURL }}
                    region: {{ .Values.openstack.region }}
                    {{- if .Values.openstack.useApplicationCredentials }}
                    application-credential-id: {{ .Values.openstack.applicationCredentialID }}
                    application-credential-secret: {{ .Values.openstack.applicationCredentialSecret }}
                    {{- else }}
                    username: {{ .Values.openstack.username }}
                    {{- end }}
                secret:
                  enabled: true
                  name: cloud-config
                  create: false

            - name: openstack-csi
              chartname: openstack/openstack-cinder-csi
              version: 2.31.3
              order: 2
              namespace: kube-system
              values: |
                storageClass:
                  enabled: true
                  delete:
                    isDefault: false
                    allowVolumeExpansion: true
                  retain:
                    isDefault: false
                    allowVolumeExpansion: false
                