apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: {{ include "cluster.name" . }}
  annotations:
    cluster.x-k8s.io/managed-by: k0smotron
    #todobnr
  finalizers:
  - hmc.mirantis.com/cleanup
spec:
  {{- with .Values.clusterIdentity }}
  identityRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  networkSpec:
  #todobnr
  # check what other values should go in here
  