apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: {{ include "openstackmachinetemplate.controlplane.name" . }}
spec:
  template:
    spec:
      {{- if not ( .Values.controlplane.sshPublicKey | empty) }}
      sshPublicKey: {{ .Values.controlplane.sshPublicKey }}
      {{- end }}
      
      providerID: {{ .Values.controlplane.providerID }}
      flavor: {{ .Values.controlplane.flavor }}
      
      image:
        filter:
          name: {{ .Values.controlplane.image.filter.name }}
          tags:
            {{- range $tag := .Values.controlplane.image.filter.tags }}
            - {{ $tag }}
            {{- end }}
      
      {{- if gt (len .Values.controlplane.portOpts) 0 }}
      portOpts:
        {{ .Values.controlplane.portOpts | toYaml | nindent 8 }}
      {{- end }}

      {{- if gt (len .Values.controlplane.securityGroups) 0 }}
      securityGroups:
        {{ .Values.controlplane.securityGroups | toYaml | nindent 8 }}
      {{- end }}
