apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: {{ include "openstackmachinetemplate.controlplane.name" . }}
spec:
  template:
    spec:
      # todobnr
