---
apiVersion: v1
kind: Secret
metadata:
  name: openstack-cloud-config
  namespace: ${NAMESPACE}
stringData:
  clouds.yaml: |
    clouds:
      openstack:
        auth:
          auth_url: ${OS_AUTH_URL}
          username: ${OS_USERNAME}
          password: ${OS_PASSWORD}
          project_id: ${OS_PROJECT_ID}
          project_name: ${OS_PROJECT_NAME}
          user_domain_name: ${OS_USER_DOMAIN_NAME}
        region_name: ${OS_REGION_NAME}
        interface: ${OS_INTERFACE}
        identity_api_version: ${OS_IDENTITY_API_VERSION}
---
apiVersion: hmc.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: openstack-cluster-identity-cred
  namespace: ${NAMESPACE}
spec:
  description: OpenStack credentials
  identityRef:
    apiVersion: v1
    kind: Secret
    name: openstack-cloud-config
    namespace: ${NAMESPACE}
