---
apiVersion: v1
kind: Secret
metadata:
  name: openstack-cloud-config
  namespace: ${NAMESPACE}
stringData:
  clouds.yaml: |
    clouds:
      openstack:
        auth:
          auth_url: ${OPENSTACK_AUTH_URL}
          username: ${OPENSTACK_USERNAME}
          password: ${OPENSTACK_PASSWORD}
          project_id: ${OPENSTACK_PROJECT_ID}
          project_name: ${OPENSTACK_PROJECT_NAME}
          user_domain_name: ${OPENSTACK_USER_DOMAIN_NAME}
        region_name: ${OPENSTACK_REGION_NAME}
        interface: public
        identity_api_version: 3
---
apiVersion: hmc.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: openstack-cluster-identity-cred
  namespace: ${NAMESPACE}
spec:
  description: OpenStack credentials
  identityRef:
    apiVersion: v1
    kind: Secret
    name: openstack-cloud-config
    namespace: ${NAMESPACE}
